variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  TERM: dumb
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

jobs:
  - job: buildPulseJava
    displayName: 'Build Pulse Java'
    pool:
      vmImage: 'ubuntu-18.04'
    container: adoptopenjdk:14-jdk-hotspot
    steps:
      - script: ./mvnw package
        displayName: 'Build'
      - task: CopyFiles@2
        displayName: 'Copy Artifacts'
        inputs:
          contents: 'target/pulse-java-*.zip'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: UniversalPackages@0
        displayName: 'Publish'
        inputs:
          command: publish
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          vstsFeedPublish: 'pulse/pulse'
          vstsFeedPackagePublish: 'pulse-java'
          versionOption: custom
          versionPublish: '2.0.0-$(Build.BuildNumber)'
          packagePublishDescription: 'A Didactic Java/C++ Chess Engine'

  - job: buildPulseCppLinux
    displayName: 'Build Pulse C++ Linux'
    pool:
      vmImage: 'ubuntu-18.04'
    container: fluxroot/buildz:cpp-1.0.0
    steps:
      - script: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          make test
          make package
        displayName: 'Build'
      - task: CopyFiles@2
        displayName: 'Copy Artifacts'
        inputs:
          contents: 'build/pulse-cpp-*.zip'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: UniversalPackages@0
        displayName: 'Publish'
        inputs:
          command: publish
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          vstsFeedPublish: 'pulse/pulse'
          vstsFeedPackagePublish: 'pulse-cpp-linux'
          versionOption: custom
          versionPublish: '2.0.0-$(Build.BuildNumber)'
          packagePublishDescription: 'A Didactic Java/C++ Chess Engine'

  - job: buildPulseCppWindows
    displayName: 'Build Pulse C++ Windows'
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 ..
          cmake --build . --config Release
          ctest
          cpack -C Release
        displayName: 'Build'
      - task: CopyFiles@2
        displayName: 'Copy Artifacts'
        inputs:
          contents: 'build/pulse-cpp-*.zip'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: UniversalPackages@0
        displayName: 'Publish'
        inputs:
          command: publish
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          vstsFeedPublish: 'pulse/pulse'
          vstsFeedPackagePublish: 'pulse-cpp-windows'
          versionOption: custom
          versionPublish: '2.0.0-$(Build.BuildNumber)'
          packagePublishDescription: 'A Didactic Java/C++ Chess Engine'
