version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: ./mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: ./mvnw test

      - store_test_results:
          path: target/surefire-reports
