on: push
jobs:
  build-java-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.6+10'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :pulse-java:build

  build-kotlin-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.6+10'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :pulse-kotlin:linuxDistTar

  build-kotlin-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.6+10'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :pulse-kotlin:windowsDistZip

  build-cpp-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release

  build-cpp-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release

  build-go-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: pulse-go/go.sum
      - name: Build
        working-directory: ${{github.workspace}}/pulse-go
        run: go build -v ./...
      - name: Test
        working-directory: ${{github.workspace}}/pulse-go
        run: go test -v ./...

  build-go-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: pulse-go/go.sum
      - name: Build
        working-directory: ${{github.workspace}}/pulse-go
        run: go build -v ./...
      - name: Test
        working-directory: ${{github.workspace}}/pulse-go
        run: go test -v ./...
